CREATE TABLE auth (
    auth_id INTEGER NOT NULL AUTO_INCREMENT,
    `add` INTEGER,
    create_time DATETIME(6),
    del INTEGER,
    field_add VARCHAR(255),
    field_get VARCHAR(255),
    field_set VARCHAR(255),
    `get` INTEGER,
    mod_name VARCHAR(255),
    `mode` VARCHAR(255),
    `option` VARCHAR(255),
    page_title VARCHAR(255),
    path VARCHAR(255),
    position VARCHAR(255),
    `set` INTEGER,
    table_name VARCHAR(255),
    table_nav BIT,
    table_nav_name VARCHAR(255),
    update_time DATETIME(6),
    user_group VARCHAR(255),
    PRIMARY KEY (auth_id)
) ENGINE=InnoDB;